### ISSUE TITLE
MSU-1 Patch Incompatible + "Dr. Light" to "Dr. Right"

### ISSUE THREAD

**Issue by Nigoli** [Her-Saki/Rockmania_X2#1]
Hello,

Thank you for making this patch. It's my favorite game in the series of X games and I did a playthrough yesterday. Dr. Right being named the way he was is the only thing that concerned me. I'm not sure if X1 is like that or if there's a reasoning for this. I noticed that in the Japanese version of X2, Zero's Body parts are named Zero's torso. I think in the context it works fine because you're talking about Zero's body and it's a way to differentiate between the two.

Anyway, with this patch. MSU-1 patches that would work with this game before became broken. Your translation patch is a standard on the Japanese version of the MSU-1 patch on Zeldix.net for X1. Since there is no existing source code for X2, this is a bit of a problem and can't be fixed easily. I'm told by the user Conn on Zeldix that shifting any of the code changed in the Translation patch @ 0x7E77 to somewhere else would fix the problem. Since the MSU-1 patch utilizes this.

https://www.zeldix.net/t1441p50-mega-man-x3#34843 <- Here's a link to this post.

I also want to say that you are doing justice by making this for the fans who wanted to play a more honest translation, want the Japanese terminology and not localized translations done completely wrong. I'm also hopeful that an X3 will happen at some point from you.

Best regards.

**Comment by Her-Saki** [comment]
Hello. I'm glad the patch was well-received. If moving the code is enough,
I'll make a copy and flag it as MSU-compatible. However, I would need you
to confirm that it effectively works, and if anything else needs to change.
And yes, X3 is on the list.

Best regards.

**Comment by Nigoli** [comment]
Thank you for the response.

Please let me know. I will do a playthrough to verify things are normal for it.

Thank you!

**Comment by ghost** [comment]
Thanks for your help Her-Saki :D
This isn't my msu-1 code and thus I don't have any source - I can only remap it by hex editing, so if you could shift your code would safe a lot of work.

- The msu code uses 0x7e77-0x7f8f, so you can safely use 0x7f90 for the jml to $31B000
e.g.,
```
;=====================
;Jump to jump to main routine
;=====================
org $670A
JMP $FF90

MainJump:
;==========================
org $7F90
JMP $31B000
```

- The data from 7e80-7e7f should be moved elsewhere. I couldn't find the table in your source but I think it is addressed by !ShiftData        = $80FE80   ;;Shift table address

- Also the msu code uses free space from 0x47db0-0x47ecf (this is not used in your current patch, so please don't move data here ;) )

No hooks that the msu code uses are conflicting with your hooks or other code conflicts in any way.

**Comment by Nigoli** [comment]
With the new ips patch in the latest commit. Performing an 100% playthrough, collecting all of Zero's Parts and finishing the game. Then using passwords to bring up the dialogues without collecting Zero's Parts and finishing the game again. I have not found any issues with the game.

Patched with the newest ips, then the most current MSU-1 patch in that order. Tested with SD2SNES Pro 1.10.3 sgb03.

Thank you both for making this possible for me.

Thank you for making the patch compatible, Her-Saki. I loved it when you did X1, and I cannot get enough of this X2 patch.  I cannot wait to play X3 translated properly.
